### ISSUE TITLE
Causes many warnings when used with puppet-ghostscript

### ISSUE THREAD

**Issue by RepublicOfAppsLLC** [boxen/puppet-imagemagick#9]
See also https://github.com/boxen/puppet-ghostscript/issues/2

I get tons of errors like

Referenced from: /opt/boxen/homebrew/bin/gs
  Reason: image not found
dyld: Library not loaded: /opt/boxen/homebrew/lib/libfontconfig.1.dylib
  Referenced from: /opt/boxen/homebrew/bin/gs
  Reason: image not found
identify: delegate library support not built-in `/opt/boxen/homebrew/share/ghostscript/fonts/n019003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/1529.
identify:`%s' (%d) "gs" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" -g984x24  "-sOutputFile=/var/tmp/magick-87488nA9SpH8k5KXe" "-f/var/tmp/magick-87488LS8ynCNIVqQB" "-f/var/tmp/magick-87488ZAmMSInhaO9i" @ error/utility.c/SystemCommand/1890.
identify: `%s' (%d) "gs" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" -g984x24  "-sOutputFile=/var/tmp/magick-87488nA9SpH8k5KXe" "-f/var/tmp/magick-87488LS8ynCNIVqQB" "-f/var/tmp/magick-87488ZAmMSInhaO9i" -c showpage @ error/utility.c/SystemCommand/1890.
identify: Postscript delegate failed`/var/tmp/magick-87488hCiTwupbBDDx': No such file or directory @ error/ps.c/ReadPSImage/833.
identify: unable to get type metrics `/var/folders/qb/h7k0hm7j541fmv8njm8l_5wm0000gn/T/stream20140205-72961-zfanwl.txt' @ error/txt.c/ReadTEXTImage/257.
dyld: Library not loaded: /opt/boxen/homebrew/lib/libfontconfig.1.dylib
  Referenced from: /opt/boxen/homebrew/bin/gs
  Reason: image not found
dyld: Library not loaded: /opt/boxen/homebrew/lib/libfontconfig.1.dylib
  Referenced from: /opt/boxen/homebrew/bin/gs
  Reason: image not found
identify: delegate library support not built-in`/opt/boxen/homebrew/share/ghostscript/fonts/n019003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/1529.
identify: `%s' (%d) "gs" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" -g984x24  "-sOutputFile=/var/tmp/magick-87493n4Y4w8zwVjm1" "-f/var/tmp/magick-87493XkrTsg34DMNl" "-f/var/tmp/magick-87493zpURjJz5S1rT" @ error/utility.c/SystemCommand/1890.
identify:`%s' (%d) "gs" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" -g984x24  "-sOutputFile=/var/tmp/magick-87493n4Y4w8zwVjm1" "-f/var/tmp/magick-87493XkrTsg34DMNl" "-f/var/tmp/magick-87493zpURjJz5S1rT" -c showpage @ error/utility.c/SystemCommand/1890.
identify: Postscript delegate failed `/var/tmp/magick-87493FYx4SZxufTZJ': No such file or directory @ error/ps.c/ReadPSImage/833.
identify: unable to get type metrics`/var/folders/qb/h7k0hm7j541fmv8njm8l_5wm0000gn/T/stream20140205-72961-zfanwl.txt' @ error/txt.c/ReadTEXTImage/257.

Please fix or let me know how to correct this.

Thanks!

**Comment by jacobbednarz** [comment]
Deprecated in favour of [brewcask][1] and [Boxen's in built support for
homebrew/brewcask][2].

[1]: https://caskroom.github.io/
[2]: https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17
